# Generated by Django 4.2.11 on 2024-04-05 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_app', '0002_user_is_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_bench_member',
            field=models.BooleanField(default=False),
        ),
    ]
